### ISSUE TITLE
Inquiry on the Release Date for Experimental Code

### ISSUE THREAD

**Issue by vkeilo** [chenchen-usyd/AMG#1]
Hi,

I am very interested in your project and have been following its development closely. I've read about the experiments in the related paper and am eager to try them out myself.

Could you please provide an estimated timeline for when the full experimental code will be released? Your work is very inspiring, and I am looking forward to diving deeper into it.

Thank you for your time and effort.

**Comment by chenchen-usyd** [comment]
Hi vkeilo,

Thank you for your interest and kind words! The full experimental code has already been released, please check out the README for detailed instructions. The experimental code for iDDPM on the CIFAR-10 dataset and Stable Diffusion on the LAION dataset are organized in two submodules, where we have built our code based on the official codebases of iDDPM and Stable Diffusion respectively.

Please let me know if you have any further questions. Thank you!
Best regards,
Chen
